name: soarhevn
favicon: null
layout_spectrum: 0.040932211792096496
typography_spectrum: 0.9138117365073413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8811556182336062
  lightness: 0.37313139950856566
  saturation: 0.653156214626506
  rhythmicContrast: 0.44161855103448033
purpose: []
